In [1]:
# ==========================================
# ChainShield AI
# Supply Chain Risk Prediction
# ==========================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import warnings
warnings.filterwarnings("ignore")

print("Libraries Imported Successfully ✅")

Libraries Imported Successfully ✅

In [2]:
df = pd.read_csv("DataCoSupplyChainDataset.csv", encoding="latin1")

In [3]:
print("Shape :", df.shape)

df.head()

Shape : (19895, 53)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0.0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0.0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0.0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0.0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0.0,1/15/2018 11:24,Standard Class

In [4]:
# Basic Information

print("Shape:", df.shape)

print("\n\nColumns:\n")
print(df.columns)

print("\n\nData Types:\n")
print(df.dtypes)

print("\n\nMissing Values:\n")
print(df.isnull().sum())

print("\n\nStatistical Summary:\n")
df.describe()

Shape: (19895, 53)


Columns:

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')


Data Types:

Type                              object
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Id                        int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Email                    object
Customer Fname                    object
Customer Id                        int64
Customer Lname                    object
Customer Password                 object
Customer Segment                  object
Customer State                    object
Customer Street                   object
Customer Zipcode                   int64
Department Id                      int64
Department Name                   object
Latitude                         float64
Longitude                        float64
Market                            object
Order City                        object
Order Country                     object
Order Customer Id                  int64
order date (DateOrders)           object
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                      object
Order State                       object
Order Status                      object
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                     object
Product Name                      object
Product Price                    float64
Product Status                   float64
shipping date (DateOrders)        object
Shipping Mode                     object
dtype: object


Missing Values:

Type                                 0
Days for shipping (real)             0
Days for shipment (scheduled)        0
Benefit per order                    0
Sales per customer                   0
Delivery Status                      0
Late_delivery_risk                   0
Category Id                          0
Category Name                        0
Customer City                        0
Customer Country                     0
Customer Email                       0
Customer Fname                       0
Customer Id                          0
Customer Lname                       0
Customer Password                    0
Customer Segment                     0
Customer State                       0
Customer Street                      0
Customer Zipcode                     0
Department Id                        0
Department Name                      0
Latitude                             0
Longitude                            0
Market                               0
Order City                           0
Order Country                        0
Order Customer Id                    0
order date (DateOrders)              0
Order Id                             0
Order Item Cardprod Id               0
Order Item Discount                  0
Order Item Discount Rate             0
Order Item Id                        0
Order Item Product Price             0
Order Item Profit Ratio              0
Order Item Quantity                  0
Sales                                0
Order Item Total                     0
Order Profit Per Order               0
Order Region                         0
Order State                          0
Order Status                         0
Order Zipcode                    17374
Product Card Id                      0
Product Category Id                  0
Product Description              19895
Product Image                        0
Product Name                         1
Product Price                        1
Product Status                       1
shipping date (DateOrders)           1
Shipping Mode                        1
dtype: int64


Statistical Summary:

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,19895.000000,19895.000000,19895.000000,19895.000000,19895.000000,19895.000000,19895.000000,19895.000000,19895.000000,19895.000000,...,19895.000000,19895.000000,19895.000000,19895.000000,2521.000000,19895.000000,19895.000000,0.0,19894.000000,19894.0
mean,3.505001,2.882081,22.864593,187.134205,0.573561,25.677004,6880.542599,36217.864790,4.657753,29.855386,...,2.597286,208.502031,187.134205,22.864593,54909.424435,547.952702,25.677004,NaN,118.285881,0.0
std,1.591031,1.355324,112.473482,128.979619,0.494572,15.469289,4358.391410,37611.365167,1.563003,9.778508,...,1.593118,142.878437,128.979619,112.473482,31862.079934,318.525602,15.469289,NaN,139.572126,0.0
min,0.000000,0.000000,-3366.000000,8.470000,0.000000,2.000000,1.000000,603.000000,2.000000,17.982491,...,1.000000,11.290000,8.470000,-3366.000000,1453.000000,19.000000,2.000000,NaN,11.290000,0.0
25%,2.000000,2.000000,7.630000,105.580002,0.000000,17.000000,3304.000000,725.000000,4.000000,18.265020,...,1.000000,119.980003,105.580002,7.630000,22901.000000,365.000000,17.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,32.110001,161.970001,1.000000,24.000000,6635.000000,20002.000000,4.000000,33.403561,...,2.000000,179.970001,161.970001,32.110001,60505.000000,502.000000,24.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,67.220001,251.979996,1.000000,29.000000,9986.000000,78520.000000,5.000000,39.323830,...,4.000000,299.950012,251.979996,67.220001,89015.000000,627.000000,29.000000,NaN,129.990005,0.0
max,6.000000,4.000000,684.000000,1759.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1759.989990,684.000000,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19895 entries, 0 to 19894
Data columns (total 53 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Type                           19895 non-null  object
 1   Days for shipping (real)       19895 non-null  int64
 2   Days for shipment (scheduled)  19895 non-null  int64
 3   Benefit per order              19895 non-null  float64
 4   Sales per customer             19895 non-null  float64
 5   Delivery Status                19895 non-null  object
 6   Late_delivery_risk             19895 non-null  int64
 7   Category Id                    19895 non-null  int64
 8   Category Name                  19895 non-null  object
 9   Customer City                  19895 non-null  object
 10  Customer Country               19895 non-null  object
 11  Customer Email                 19895 non-null  object
 12  Customer Fname                 19895 non-null  object
 13  Customer Id                    19895 non-null  int64
 14  Customer Lname                 19895 non-null  object
 15  Customer Password              19895 non-null  object
 16  Customer Segment               19895 non-null  object
 17  Customer State                 19895 non-null  object
 18  Customer Street                19895 non-null  object
 19  Customer Zipcode               19895 non-null  int64
 20  Department Id                  19895 non-null  int64
 21  Department Name                19895 non-null  object
 22  Latitude                       19895 non-null  float64
 23  Longitude                      19895 non-null  float64
 24  Market                         19895 non-null  object
 25  Order City                     19895 non-null  object
 26  Order Country                  19895 non-null  object
 27  Order Customer Id              19895 non-null  int64
 28  order date (DateOrders)        19895 non-null  object
 29  Order Id                       19895 non-null  int64
 30  Order Item Cardprod Id         19895 non-null  int64
 31  Order Item Discount            19895 non-null  float64
 32  Order Item Discount Rate       19895 non-null  float64
 33  Order Item Id                  19895 non-null  int64
 34  Order Item Product Price       19895 non-null  float64
 35  Order Item Profit Ratio        19895 non-null  float64
 36  Order Item Quantity            19895 non-null  int64
 37  Sales                          19895 non-null  float64
 38  Order Item Total               19895 non-null  float64
 39  Order Profit Per Order         19895 non-null  float64
 40  Order Region                   19895 non-null  object
 41  Order State                    19895 non-null  object
 42  Order Status                   19895 non-null  object
 43  Order Zipcode                  2521 non-null   float64
 44  Product Card Id                19895 non-null  int64
 45  Product Category Id            19895 non-null  int64
 46  Product Description            0 non-null      float64
 47  Product Image                  19895 non-null  object
 48  Product Name                   19894 non-null  object
 49  Product Price                  19894 non-null  float64
 50  Product Status                 19894 non-null  float64
 51  shipping date (DateOrders)     19894 non-null  object
 52  Shipping Mode                  19894 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 8.0+ MB

In [6]:
df["Late_delivery_risk"].value_counts()

Late_delivery_risk
1    11411
0     8484
Name: count, dtype: int64

In [7]:
# Columns to remove

drop_columns = [
    "Customer Email",
    "Customer Fname",
    "Customer Lname",
    "Customer Password",
    "Customer Id",
    "Customer Street",
    "Customer Zipcode",
    "Latitude",
    "Longitude",
    "Order Id",
    "Order Customer Id",
    "Order Item Cardprod Id",
    "Product Card Id",
    "Product Description",
    "Product Image",
    "Product Name",
    "Order Zipcode"
]

df = df.drop(columns=drop_columns)

print("Remaining Columns:", df.shape[1])

df.head()

Remaining Columns: 36

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Category Id,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,73,327.75,0.0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,311.359985,-249.089996,South Asia,Rajastán,PENDING,73,327.75,0.0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,309.720001,-247.779999,South Asia,Rajastán,CLOSED,73,327.75,0.0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,304.809998,22.860001,Oceania,Queensland,COMPLETE,73,327.75,0.0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,73,327.75,0.0,1/15/2018 11:24,Standard Class

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19895 entries, 0 to 19894
Data columns (total 36 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Type                           19895 non-null  object
 1   Days for shipping (real)       19895 non-null  int64
 2   Days for shipment (scheduled)  19895 non-null  int64
 3   Benefit per order              19895 non-null  float64
 4   Sales per customer             19895 non-null  float64
 5   Delivery Status                19895 non-null  object
 6   Late_delivery_risk             19895 non-null  int64
 7   Category Id                    19895 non-null  int64
 8   Category Name                  19895 non-null  object
 9   Customer City                  19895 non-null  object
 10  Customer Country               19895 non-null  object
 11  Customer Segment               19895 non-null  object
 12  Customer State                 19895 non-null  object
 13  Department Id                  19895 non-null  int64
 14  Department Name                19895 non-null  object
 15  Market                         19895 non-null  object
 16  Order City                     19895 non-null  object
 17  Order Country                  19895 non-null  object
 18  order date (DateOrders)        19895 non-null  object
 19  Order Item Discount            19895 non-null  float64
 20  Order Item Discount Rate       19895 non-null  float64
 21  Order Item Id                  19895 non-null  int64
 22  Order Item Product Price       19895 non-null  float64
 23  Order Item Profit Ratio        19895 non-null  float64
 24  Order Item Quantity            19895 non-null  int64
 25  Sales                          19895 non-null  float64
 26  Order Item Total               19895 non-null  float64
 27  Order Profit Per Order         19895 non-null  float64
 28  Order Region                   19895 non-null  object
 29  Order State                    19895 non-null  object
 30  Order Status                   19895 non-null  object
 31  Product Category Id            19895 non-null  int64
 32  Product Price                  19894 non-null  float64
 33  Product Status                 19894 non-null  float64
 34  shipping date (DateOrders)     19894 non-null  object
 35  Shipping Mode                  19894 non-null  object
dtypes: float64(11), int64(8), object(17)
memory usage: 5.5+ MB

In [9]:
# Check missing values

missing = df.isnull().sum()

missing = missing[missing > 0]

print(missing)

Product Price                 1
Product Status                1
shipping date (DateOrders)    1
Shipping Mode                 1
dtype: int64

In [10]:
# Remove rows with missing values

df = df.dropna()

print("New Shape:", df.shape)
print("Remaining Missing Values:", df.isnull().sum().sum())

New Shape: (19894, 36)
Remaining Missing Values: 0

In [11]:
from sklearn.preprocessing import LabelEncoder

# Copy dataset
encoded_df = df.copy()

# Store encoders for future use
label_encoders = {}

# Encode all object columns
for column in encoded_df.select_dtypes(include="object").columns:
    le = LabelEncoder()
    encoded_df[column] = le.fit_transform(encoded_df[column])
    label_encoders[column] = le

print("✅ Encoding Completed")
encoded_df.head()

✅ Encoding Completed

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Category Id,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,1,3,4,91.250000,314.640015,0,0,73,34,65,...,314.640015,91.250000,15,398,2,73,327.75,0.0,5123,3
1,3,5,4,-249.089996,311.359985,1,1,73,34,65,...,311.359985,-249.089996,13,695,5,73,327.75,0.0,529,3
2,0,4,4,-247.779999,309.720001,3,0,73,34,450,...,309.720001,-247.779999,13,695,1,73,327.75,0.0,477,3
3,1,3,4,22.860001,304.809998,0,0,73,34,283,...,304.809998,22.860001,11,689,2,73,327.75,0.0,415,3
4,2,2,4,134.210007,298.250000,0,0,73,34,65,...,298.250000,134.210007,11,689,6,73,327.75,0.0,339,3

In [12]:
encoded_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19894 entries, 0 to 19893
Data columns (total 36 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Type                           19894 non-null  int64
 1   Days for shipping (real)       19894 non-null  int64
 2   Days for shipment (scheduled)  19894 non-null  int64
 3   Benefit per order              19894 non-null  float64
 4   Sales per customer             19894 non-null  float64
 5   Delivery Status                19894 non-null  int64
 6   Late_delivery_risk             19894 non-null  int64
 7   Category Id                    19894 non-null  int64
 8   Category Name                  19894 non-null  int64
 9   Customer City                  19894 non-null  int64
 10  Customer Country               19894 non-null  int64
 11  Customer Segment               19894 non-null  int64
 12  Customer State                 19894 non-null  int64
 13  Department Id                  19894 non-null  int64
 14  Department Name                19894 non-null  int64
 15  Market                         19894 non-null  int64
 16  Order City                     19894 non-null  int64
 17  Order Country                  19894 non-null  int64
 18  order date (DateOrders)        19894 non-null  int64
 19  Order Item Discount            19894 non-null  float64
 20  Order Item Discount Rate       19894 non-null  float64
 21  Order Item Id                  19894 non-null  int64
 22  Order Item Product Price       19894 non-null  float64
 23  Order Item Profit Ratio        19894 non-null  float64
 24  Order Item Quantity            19894 non-null  int64
 25  Sales                          19894 non-null  float64
 26  Order Item Total               19894 non-null  float64
 27  Order Profit Per Order         19894 non-null  float64
 28  Order Region                   19894 non-null  int64
 29  Order State                    19894 non-null  int64
 30  Order Status                   19894 non-null  int64
 31  Product Category Id            19894 non-null  int64
 32  Product Price                  19894 non-null  float64
 33  Product Status                 19894 non-null  float64
 34  shipping date (DateOrders)     19894 non-null  int64
 35  Shipping Mode                  19894 non-null  int64
dtypes: float64(11), int64(25)
memory usage: 5.6 MB

In [13]:
# Features (X) and Target (y)

X = encoded_df.drop("Late_delivery_risk", axis=1)
y = encoded_df["Late_delivery_risk"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (19894, 35)
Target Shape: (19894,)

In [14]:
from sklearn.model_selection import train_test_split

# Split dataset

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data:", X_train.shape)
print("Testing Data :", X_test.shape)

Training Data: (15915, 35)
Testing Data : (3979, 35)

In [15]:
from sklearn.linear_model import LogisticRegression

# Create model
lr_model = LogisticRegression(max_iter=1000)

# Train model
lr_model.fit(X_train, y_train)

print("✅ Logistic Regression Model Trained Successfully")

✅ Logistic Regression Model Trained Successfully

In [16]:
# Predictions

y_pred = lr_model.predict(X_test)

print(y_pred[:10])

[1 1 1 1 1 1 0 0 1 1]

In [17]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

Accuracy : 0.6288012063332495
Precision: 0.6344803370786517
Recall   : 0.8056174765938475
F1 Score : 0.7098801807110587

In [18]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))

print()

print(classification_report(y_test, y_pred))

[[ 695 1041]
 [ 436 1807]]

              precision    recall  f1-score   support

           0       0.61      0.40      0.48      1736
           1       0.63      0.81      0.71      2243

    accuracy                           0.63      3979
   macro avg       0.62      0.60      0.60      3979
weighted avg       0.63      0.63      0.61      3979

In [19]:
from sklearn.ensemble import RandomForestClassifier

# Create model
rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

# Train model
rf_model.fit(X_train, y_train)

print("✅ Random Forest Trained Successfully")

✅ Random Forest Trained Successfully

In [20]:
# Random Forest Predictions

rf_pred = rf_model.predict(X_test)

print(rf_pred[:10])

[0 1 1 1 0 1 0 0 1 0]

In [21]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, rf_pred)
precision = precision_score(y_test, rf_pred)
recall = recall_score(y_test, rf_pred)
f1 = f1_score(y_test, rf_pred)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

In [22]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, rf_pred))

print()

print(classification_report(y_test, rf_pred))

[[1736    0]
 [   0 2243]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1736
           1       1.00      1.00      1.00      2243

    accuracy                           1.00      3979
   macro avg       1.00      1.00      1.00      3979
weighted avg       1.00      1.00      1.00      3979

In [23]:
leakage_columns = [
    "Delivery Status",
    "Days for shipping (real)"
]

In [24]:
# Remove leakage columns
new_df = encoded_df.drop(columns=leakage_columns)

print("New Shape:", new_df.shape)
new_df.head()

New Shape: (19894, 34)

,Type,Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Segment,...,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Category Id,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,1,4,91.250000,314.640015,0,73,34,65,1,0,...,314.640015,91.250000,15,398,2,73,327.75,0.0,5123,3
1,3,4,-249.089996,311.359985,1,73,34,65,1,0,...,311.359985,-249.089996,13,695,5,73,327.75,0.0,529,3
2,0,4,-247.779999,309.720001,0,73,34,450,0,0,...,309.720001,-247.779999,13,695,1,73,327.75,0.0,477,3
3,1,4,22.860001,304.809998,0,73,34,283,0,2,...,304.809998,22.860001,11,689,2,73,327.75,0.0,415,3
4,2,4,134.210007,298.250000,0,73,34,65,1,1,...,298.250000,134.210007,11,689,6,73,327.75,0.0,339,3

In [25]:
X = new_df.drop("Late_delivery_risk", axis=1)
y = new_df["Late_delivery_risk"]

print(X.shape)
print(y.shape)

(19894, 33)
(19894,)

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [27]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)

In [28]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

rf_pred = rf_model.predict(X_test)

print("Accuracy :", accuracy_score(y_test, rf_pred))
print("Precision:", precision_score(y_test, rf_pred))
print("Recall   :", recall_score(y_test, rf_pred))
print("F1 Score :", f1_score(y_test, rf_pred))

Accuracy : 0.7489318924352852
Precision: 0.832620320855615
Recall   : 0.6941596076683014
F1 Score : 0.7571115973741794

In [29]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, rf_pred))
print(classification_report(y_test, rf_pred))

[[1423  313]
 [ 686 1557]]
              precision    recall  f1-score   support

           0       0.67      0.82      0.74      1736
           1       0.83      0.69      0.76      2243

    accuracy                           0.75      3979
   macro avg       0.75      0.76      0.75      3979
weighted avg       0.76      0.75      0.75      3979

In [30]:
more_leakage = [
    "Order Status",
    "shipping date (DateOrders)"
]

new_df = new_df.drop(columns=more_leakage)

In [31]:
# ===========================================
# Final Training for Production
# ===========================================

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Final feature set
X = new_df.drop("Late_delivery_risk", axis=1)
y = new_df["Late_delivery_risk"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

predictions = rf_model.predict(X_test)

print("Production Accuracy:", accuracy_score(y_test, predictions))

Production Accuracy: 0.7225433526011561

In [32]:
# ===========================================
# Save the Production Model
# ===========================================

import joblib

# Save the trained Random Forest model
joblib.dump(rf_model, "chainshield_model.pkl")

# Save feature names (VERY IMPORTANT)
joblib.dump(list(X.columns), "feature_names.pkl")

# NEW
joblib.dump(label_encoders, "label_encoders.pkl")

print("✅ Model saved successfully!")
print("✅ Feature names saved successfully!")
print("✅ Label Encoders Saved")

✅ Model saved successfully!
✅ Feature names saved successfully!
✅ Label Encoders Saved

In [33]:
# ===========================================
# Verify Saved Model
# ===========================================

import joblib

loaded_model = joblib.load("chainshield_model.pkl")
feature_names = joblib.load("feature_names.pkl")

print("Model loaded successfully!")
print()

print("Number of features:", len(feature_names))
print()

print("First 10 features:")
print(feature_names[:10])

Model loaded successfully!

Number of features: 31

First 10 features:
['Type', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer', 'Category Id', 'Category Name', 'Customer City', 'Customer Country', 'Customer Segment', 'Customer State']

In [34]:
from google.colab import files

files.download("chainshield_model.pkl")
files.download("feature_names.pkl")
files.download("label_encoders.pkl")